export const FIELD_DATA: Array<{ name: string; hectares: number }> = [
    // Small fields (2-10 ha) - ~15 fields
    { name: "Small Pasture", hectares: 3.2 },
    { name: "Corner Lot", hectares: 2.8 },
    { name: "Edge Field", hectares: 4.5 },
    { name: "Near Field", hectares: 5.1 },
    { name: "Fifth Field", hectares: 6.3 },
    { name: "Fourth Field", hectares: 7.8 },
    { name: "Third Field", hectares: 8.2 },
    { name: "Second Field", hectares: 9.5 },
    { name: "First Field", hectares: 3.7 },
    { name: "Old Orchard", hectares: 4.9 },
    { name: "Pine Field", hectares: 6.7 },
    { name: "Oak Meadow", hectares: 5.4 },
    { name: "Maple Acre", hectares: 7.1 },
    { name: "Birch Pasture", hectares: 4.2 },
    { name: "Cedar Field", hectares: 8.9 },
    
    // Medium fields (10-50 ha) - ~25 fields
    { name: "North Pasture", hectares: 45.2 },
    { name: "South Meadow", hectares: 32.8 },
    { name: "East Field", hectares: 28.5 },
    { name: "West Acreage", hectares: 35.7 },
    { name: "River Bottom", hectares: 42.3 },
    { name: "Hill Top", hectares: 18.6 },
    { name: "Valley View", hectares: 25.4 },
    { name: "Sunset Ridge", hectares: 38.9 },
    { name: "Main Field", hectares: 48.1 },
    { name: "Back Forty", hectares: 40.0 },
    { name: "Lower Field", hectares: 22.3 },
    { name: "Upper Field", hectares: 19.7 },
    { name: "Northwest Corner", hectares: 15.8 },
    { name: "Southeast Plot", hectares: 27.2 },
    { name: "Big Field", hectares: 46.5 },
    { name: "Long Meadow", hectares: 33.1 },
    { name: "Johnson's Field", hectares: 29.6 },
    { name: "Miller's Acre", hectares: 24.8 },
    { name: "New Pasture", hectares: 16.4 },
    { name: "Home Field", hectares: 21.9 },
    { name: "Far Field", hectares: 31.5 },
    { name: "Top Field", hectares: 14.2 },
    { name: "Bottom Field", hectares: 17.6 },
    { name: "Middle Field", hectares: 23.4 },
    { name: "Central Field", hectares: 26.7 },
    { name: "Green Pasture", hectares: 37.3 },
    { name: "Golden Field", hectares: 41.8 },
    { name: "Spring Meadow", hectares: 20.5 },
    { name: "Summer Field", hectares: 34.6 },
    { name: "Autumn Acre", hectares: 13.9 },
    { name: "Winter Pasture", hectares: 30.2 },
    { name: "North Forty", hectares: 39.4 },
    { name: "South Forty", hectares: 36.1 },
    { name: "East Forty", hectares: 43.7 },
    { name: "West Forty", hectares: 44.9 },
    
    // Large fields (50-150 ha) - ~10 fields
    { name: "Grand Meadow", hectares: 87.3 },
    { name: "Wide Acreage", hectares: 95.6 },
    { name: "Expansive Field", hectares: 72.4 },
    { name: "Broad Pasture", hectares: 128.7 },
    { name: "Vast Bottom", hectares: 142.3 },
    { name: "High Ridge", hectares: 68.9 },
    { name: "Deep Valley", hectares: 115.2 },
    { name: "Long Ridge", hectares: 103.5 },
    { name: "Master Field", hectares: 134.8 },
    { name: "Great Forty", hectares: 76.1 },
]
